### ISSUE TITLE
Output optionally should ignore warnings

### ISSUE THREAD

**Issue by sjPlot** [sjPlot/Relaunch64#12]
Would it be possible to make the output ignore warnings? Seems TASS 64 doesn't have a straight print, so you have to do .warn which then gets caught as an error in Relaunched 64.

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Would it be possible to make the output ignore warnings? Seems TASS 64 
> doesn't have a straight print, so you have to do .warn which then gets 
> caught as an error in Relaunched 64.

The readErrorLines function could be updated ignore warnings and only process
the rest. This I think would be interesting for other assemblers too.

Do you think it'd be useful to have a new option weather to ignore warnings or
not in Relaunch64?

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlVXfeIACgkQyBOVYiJltRZnmgCeJgcyf3fm04NErBzBxhLSL+V7
stkAoOVLQvrN4NBjs4aBVWfA1TwGOevk
=nKfV
-----END PGP SIGNATURE-----

**Comment by sjPlot** [comment]
I copied this issue from lemon64: http://www.lemon64.com/forum/viewtopic.php?p=678049#678049

I would say yes we should add an option to whether ignore warnings or not. A checkbox in the settings, or a checkbox somewhere "on the fly"?

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> I copied this issue from lemon64: 
> http://www.lemon64.com/forum/viewtopic.php?p=678049#678049
> 
> I would say yes we should add an option to whether ignore warnings or 
> not. A checkbox in the settings, or a checkbox somewhere "on the fly"?

Same place where the assembler is selected, so I think it's in the settings.

I've updated the assembler message parsers with a parameter for selecting
this. Only one was tested, rest should in theory work the same way. Maybe
it'd be worth to try the Kick one as that's a bit more complicated as the
fault message is split on two lines.

- -- 
- -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlVXpMAACgkQyBOVYiJltRbOOgCfUl1XwT/LesenmTi9aHh176IL
gboAoNVqrs6WCiwsIuG1t5KlGh2Vgj/X
=Vatl
-----END PGP SIGNATURE-----

**Comment by sjPlot** [comment]
Thanks, I'll update the settings and GUI the next days and do some tests.

**Comment by CINJ** [comment]
It would be cool to associate 'action' to 'compiler output state'. So you
can deal with errors, warnings and info in a modular way per compiler and
let any state:action be user configured - actions could be suppress, pipe
to executable, output.

J

On Sunday, May 17, 2015, soci64 <notifications@github.com> wrote:

> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA1
>
> > Would it be possible to make the output ignore warnings? Seems TASS 64
> > doesn't have a straight print, so you have to do .warn which then gets
> > caught as an error in Relaunched 64.
>
> The readErrorLines function could be updated ignore warnings and only
> process
> the rest. This I think would be interesting for other assemblers too.
>
> Do you think it'd be useful to have a new option weather to ignore
> warnings or
> not in Relaunch64?
>
> - --
> -soci-
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v1
>
> iEYEARECAAYFAlVXfeIACgkQyBOVYiJltRZnmgCeJgcyf3fm04NErBzBxhLSL+V7
> stkAoOVLQvrN4NBjs4aBVWfA1TwGOevk
> =nKfV
> -----END PGP SIGNATURE-----
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sjPlot/Relaunch64/issues/12#issuecomment-102657406>.
>


-- 

Joe Cincotta. managing director
+61 2 8517 5080   P
+61 419 694 030   M
www.pixolut.com  W

[image: Logo]



This e-mail and any files transmitted with it may contain confidential
information and is intended
solely for use by the individual to whom it is addressed. If you received
this e-mail in error, please
notify the sender, do not disclose its contents to others and delete it
from your system.

**Comment by sjPlot** [comment]
I'm adding a command-line-option feature to the compiler scripts, so you can easily trigger the ignore-warnings-option via script, and furthermore, we can add more options in the future without the need to change the GUI.

**Comment by oziphantom** [comment]
Here is an small snipped of TASS code that generates a warning as requested in Lemon 64, although it seems I'm to late. 
* = $334
test .byte 0
.warn "Size of variables = ", $400-*

**Comment by sjPlot** [comment]
No, since Release 3.3.4 is still under development, you're not too late. Thanks for the Code-snippet, I'll test it.

**Comment by sjPlot** [comment]
Seems to work. You can download the latest preview [at Sourceforge](https://sourceforge.net/projects/relaunch64/files/devel).

**Comment by oziphantom** [comment]
Yup works. thanks. 

To be picky, could it not show the line under it. So it just has
D:\GitHub\Qwack64\qwak.asm:179:1: warning: Size of variables = 144
D:\GitHub\Qwack64\qwak.asm:180:1: warning: Size of structs = 80

vs the current 
D:\GitHub\Qwack64\qwak.asm:179:1: warning: Size of variables = 144
.warn "Size of variables = ", $400-*
 ^
D:\GitHub\Qwack64\qwak.asm:180:1: warning: Size of structs = 80
...
?

**Comment by oziphantom** [comment]
Nope spoke too soon, it seems that it blocks the following lines in a script, so if you have steps post the build with tass, they don't seem to run

**Comment by oziphantom** [comment]
on windows you can add a line print test, if that is run it will give you an error msg saying can't initialise PRN ( make sure your printer is off and not connected to a virtual parallel port first ;) )

**Comment by sjPlot** [comment]
I can't reproduce what you say. How does your compile-script look like? How the source code?

**Comment by sjPlot** [comment]
As an example, I have following source

    *= $801
    .word (+), 10
    .null $9e, "4096"
    + .word 0
    
    * = $334
    test .byte 0
    .warn "Size of variables = ", $400-*
    
    *= $1000
    	lda #0
        sta $d020
        rts

and this compile-script:

    R64 -iw
    /usr/local/bin/64tass -C -a -i RSOURCEFILE -o ROUTFILE
    open /Applications/Vice64/x64.app ROUTFILE

Compiles and runs properly, without stopping the compile at warning.

**Comment by sjPlot** [comment]
@CINJ please open a new issue, so your suggestion won't get lost in the course of this discussion.

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Yup works. thanks.
> 
> To be picky, could it not show the line under it. So it just has 
> D:\GitHub\Qwack64\qwak.asm:179:1: warning: Size of variables = 144 
> D:\GitHub\Qwack64\qwak.asm:180:1: warning: Size of structs = 80
> 
> vs the current D:\GitHub\Qwack64\qwak.asm:179:1: warning: Size of 
> variables = 144 .warn "Size of variables = ", $400-* ^ 
> D:\GitHub\Qwack64\qwak.asm:180:1: warning: Size of structs = 80 ... ?

This is not something the editor should do but the assembler. I've added a
"--no-caret-diag" option now which removes those lines, they are not that
useful with an editor like this (except maybe for macro debugging). It's in
the svn as r944.

If you've trouble compiling it yourself but still want to test it then drop
a mail directly and I can give you a pre-compiled test version for win32.

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlVY+DAACgkQyBOVYiJltRYNLACg6lQ6R/QADssOxm6N57+MYGNb
s0oAoIfXGz2g2YERB4ogzisThMovPHjL
=oYbY
-----END PGP SIGNATURE-----

**Comment by oziphantom** [comment]
It doesn't stop the assemble, it stops the script. 

Code is here https://github.com/oziphantom/Qwack64 you will need to uncomment the .warn

Build script is as such
either the "build" script 
SOURCEDIR\64tass.exe -a SOURCEFILE -o OUTFILE -l SOURCENAME.label
SOURCEDIR\tassTox64Labels.exe SOURCENAME.label SOURCENAME.vice
or the build and Run script
SOURCEDIR\64tass.exe -a SOURCEFILE -o OUTFILE -l SOURCENAME.label
SOURCEDIR\tassTox64Labels.exe SOURCENAME.label SOURCENAME.vice
D:\emulation\WinVICE-2.4-x86\x64 -autostart  SOURCENAME.prg +confirmexit -reu -reusize 128 -moncommands SOURCENAME.vice

**Comment by sjPlot** [comment]
I can't compile the file because I get several other errors before:

    64tass Turbo Assembler Macro V1.51.943?
    64TASS comes with ABSOLUTELY NO WARRANTY; This is free software, and you
    are welcome to redistribute it under certain conditions; See LICENSE!
    
    Assembling file:   qwak.asm
    Assembling file:   qwak_structs.asm
    Reading file:      testattribs.raw
    Reading file:      tiledefs.raw
    Reading file:      testchars.raw
    Reading file:      sprites.bin
    Reading file:      testmap.raw
    Error messages:    6
    Warning messages:  None
    Passes:            2
    qwak.asm:229:9: error: not defined 'mPlex'
     		cpx # mPlex.kMaxSpr+1	 ;have we reached 32 yet?
     		      ^
    qwak.asm:229:9: note: searched in the global scope
    qwak.asm:686:17: error: not defined 'exitFrame'
     		sta LevelData.exitFrame
     		              ^
    qwak.asm:150:1: note: searched in this object only
     LevelData .dstruct sLevelData
     ^
    qwak.asm:1107:19: error: not defined 'Fruit'
     	lda #kScoreIndex.Fruit
     	                 ^

**Comment by oziphantom** [comment]
sorry grab again

**Comment by oziphantom** [comment]
What OS are you testing on? The don't wait when running scripts option doesn't work either. I'm on Windows 8.1.

**Comment by sjPlot** [comment]
I use both Windows 7 and OS X 10.9. I haven't had time to get back to this issue yet, but hope to find some time by this weekend.

**Comment by sjPlot** [comment]
I just downloaded the GitHub-master, but still get the errors:

```
64tass Turbo Assembler Macro V1.51.943?
64TASS comes with ABSOLUTELY NO WARRANTY; This is free software, and you
are welcome to redistribute it under certain conditions; See LICENSE!

Assembling file:   qwak.asm
Assembling file:   qwak_structs.asm
Reading file:      testattribs.raw
Reading file:      tiledefs.raw
Reading file:      testchars.raw
Reading file:      sprites.bin
Reading file:      testmap.raw
Error messages:    4
Warning messages:  1
Passes:            2
qwak.asm:230:9: error: not defined 'mPlex'
 		cpx # mPlex.kMaxSpr+1	 ;have we reached 32 yet?
 		      ^
qwak.asm:230:9: note: searched in the global scope
qwak.asm:1122:19: error: not defined 'Fruit'
 	lda #kScoreIndex.Fruit
 	                 ^
qwak.asm:1401:1: note: searched in this object only
 kScoreIndex .block
 ^
qwak.asm:1427:6: error: not defined '_notSafe'
 	beq _notSafe
 	    ^
qwak.asm:1423:1: note: searched in this object only
 checkSolidTile
 ^
qwak.asm:1864:6: error: not defined '_movefish'
 	bcc _movefish
 	    ^
qwak.asm:1653:1: note: searched in this object only
 updateEntities
 ^
```

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> I just downloaded the GitHub-master, but still get the errors:

The source seems to be written in a case insensitive manner, while you
compile it case sensitive.

The earlier mentioned "-C -a -i" is not appropriate for this source, instead
use "-a" only according to his later script. Then it compiles fine.

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlVxKNoACgkQyBOVYiJltRafbQCfScC3IwQ3EZj5n3M7uU9y4KW6
F0sAn1Zo9JZomQ0xlW1rKqWtCYd+Gh9J
=tiYF
-----END PGP SIGNATURE-----

**Comment by oziphantom** [comment]
Correct, as per the script above I don't have -C defined.

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1


Seems to work here. Is "tassTox64Labels.exe" always returning with exit code
0? If not or it's "void" then it might stop the script execution.

- -- 
						    -soci-

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlVx7vYACgkQyBOVYiJltRYG4wCfXRsE2fLosB1mPEyfh+xatlEL
edQAmgL+SsM0GBKfHEA3UrHqFH/TRcGb
=9hWg
-----END PGP SIGNATURE-----

**Comment by oziphantom** [comment]
It was void, but I changed it to int, return 0 still the same. I will add the exe to GitHub for you

**Comment by oziphantom** [comment]
also I'm using 64tass Turbo Assembler Macro V1.51.727 maybe I should update, bug in Tass?

**Comment by sjPlot** [comment]
Is this issue fixed, or do you still face problems?
@soci64 are there any current TASS-updates to be included in R64? I think I could release a new minor update the next days...

**Comment by oziphantom** [comment]
Not fixed.

**Comment by soci64** [comment]
Was the '--no-caret-diag' option ok to suppress extra output between messages?
http://tass64.sourceforge.net/#commandline-operation

Was '--vice-labels -l filename' good enough to replace the extra step of label conversion?
http://tass64.sourceforge.net/#commandline-listing

**Comment by oziphantom** [comment]
I haven't tried the --no-caret-diag option
--vice-labels is nice, still has some issues, but Relauched still stalls waiting for vice to be closed. on 20150915 Windows 10
The version of VICE wouldn't matter would it?

**Comment by soci64** [comment]
I'm not surprised that it's waiting for VICE if it's in the script, that's what it normally does. It waits for every command in the script to get the result and decides to stop or to continue.

**Comment by oziphantom** [comment]
That is what the "don't wait when running scripts" option is for, so you can run VICE and read your code at the same time.

**Comment by oziphantom** [comment]
I tested the --no-caret-diag it makes no difference to the output, running latest 64Tass

**Comment by oziphantom** [comment]
64tass Turbo Assembler Macro V1.51.992
64TASS comes with ABSOLUTELY NO WARRANTY; This is free software, and you
are welcome to redistribute it under certain conditions; See LICENSE!

Assembling file:   D:\GitHub\SquidJump\squid.asm
Reading file:      D:\GitHub\SquidJump\map.raw
Reading file:      D:\GitHub\SquidJump\attribs.raw
Reading file:      D:\GitHub\SquidJump\chars.raw
Reading file:      D:\GitHub\SquidJump\sprites.bin
Assembling file:   D:\GitHub\SquidJump\level.inc
Error messages:    None
Warning messages:  20
Passes:            3
Memory range:      $0801-$080c
Memory range:      $0810-$1c09
Memory range:      $4000-$43e7
Memory range:      $4400-$44ff
Memory range:      $4800-$5eed
D:\GitHub\SquidJump\squid.asm:197:1: warning: Game Data start = $0205
 .warn "Game Data start = ", *
 ^
D:\GitHub\SquidJump\squid.asm:199:1: warning: LevelData start = $0213
 .warn "LevelData start = ", *
 ^

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> I tested the --no-caret-diag it makes no difference to the output,
> running latest 64Tass

Please post the relaunch64 log as well, otherwise I assume it was not
applied at the correct place (the assembler invocation). It works fine here.

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlYGoK4ACgkQyBOVYiJltRaFiwCgyfOxzYjoQz/+AUoHa0uF7cgK
4EMAoIS6HP8aYMJiMsF4gncb73seEJH2
=+16v
-----END PGP SIGNATURE-----

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> That is what the "don't wait when running scripts" option is for, so you
> can run VICE and read your code at the same time.

I can confirm it blocks until it's closed irrespective of R64 -nowait or
config dialog options.

Possibly running a batch file instead and using "start" to run x64 would be
a workaround.

I'm not a fan of having "external" compile scripts, therefore I only have
one with a single "make" command. That one fits for all ;)

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEUEARECAAYFAlYGo2UACgkQyBOVYiJltRbG7QCgsLAUGoK6g6PJCan8TawF9v4M
6xIAl1wQoO2MWEjloH61EaCHM+WiAYI=
=tQW8
-----END PGP SIGNATURE-----

**Comment by oziphantom** [comment]
Above is the Log, its not all of it but I figured it had the important details, it just has more warnings on the end
Here is my build "script"
SOURCEDIR\64tass.exe -a SOURCEFILE -o OUTFILE  --no-caret-diag --vice-labels -l SOURCENAME.vice
D:\emulation\WinVICE-2.4-x86\x64 -autostart  SOURCENAME.prg +confirmexit -reu -reusize 128 -moncommands SOURCENAME.vice

**Comment by oziphantom** [comment]
So I tried the old, close the program and open it again.... just on the off chance 
64tass Turbo Assembler Macro V1.51.992
64TASS comes with ABSOLUTELY NO WARRANTY; This is free software, and you
are welcome to redistribute it under certain conditions; See LICENSE!

Assembling file:   D:\GitHub\SquidJump\squid.asm
Reading file:      D:\GitHub\SquidJump\map.raw
Reading file:      D:\GitHub\SquidJump\attribs.raw
Reading file:      D:\GitHub\SquidJump\chars.raw
Reading file:      D:\GitHub\SquidJump\sprites.bin
Assembling file:   D:\GitHub\SquidJump\level.inc
Error messages:    None
Warning messages:  20
Passes:            3
Memory range:      $0801-$080c
Memory range:      $0810-$1c43
Memory range:      $4000-$43e7
Memory range:      $4400-$44ff
Memory range:      $4800-$5eed
D:\GitHub\SquidJump\squid.asm:200:1: warning: al .GameData $0205
D:\GitHub\SquidJump\squid.asm:204:1: warning: al .LevelData $0213
D:\GitHub\SquidJump\squid.asm:208:1: warning: al .PlayerData $0215
D:\GitHub\SquidJump\squid.asm:212:1: warning: al .MapTrackingData $0229
D:\GitHub\SquidJump\squid.asm:216:1: warning: al .Score $022d
D:\GitHub\SquidJump\squid.asm:220:1: warning: al .HiScore $0233
D:\GitHub\SquidJump\squid.asm:225:1: warning: al .MovingPlatform $0239
D:\GitHub\SquidJump\squid.asm:229:1: warning: al .TickDowns $0254
D:\GitHub\SquidJump\squid.asm:235:1: warning: al .CRAMPlotColour $0256
D:\GitHub\SquidJump\squid.asm:239:1: warning: al .CRAMBorderPlotColour $0257
D:\GitHub\SquidJump\squid.asm:243:1: warning: al .FirstLineToPlot $0258
D:\GitHub\SquidJump\squid.asm:247:1: warning: al .yScroll $0259
D:\GitHub\SquidJump\squid.asm:251:1: warning: al .entitySpriteBufferHead $025a
D:\GitHub\SquidJump\squid.asm:255:1: warning: al .entitySpriteBufferTail $025b
D:\GitHub\SquidJump\squid.asm:259:1: warning: al .entitySpriteBufferPointer $025c
D:\GitHub\SquidJump\squid.asm:263:1: warning: al .ScrollDelta $025d
D:\GitHub\SquidJump\squid.asm:267:1: warning: al .NormalTemp1 $025e
D:\GitHub\SquidJump\squid.asm:271:1: warning: al .NormalTemp2 $025f
D:\GitHub\SquidJump\squid.asm:275:1: warning: al .NormalTem3 $0260
D:\GitHub\SquidJump\squid.asm:279:1: warning: al .NormalTemp4 $0261

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Above is the Log, its not all of it but I figured it had the important 
> details, it just has more warnings on the end

Looks good this time, "--no-caret-diag" seems to work.

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlYHI1kACgkQyBOVYiJltRbdewCglJ6zDMbV/IYvRrIL5pJPKUQb
c08Anih36qAC29eGKAZuqe00wvIGaNQx
=DHNp
-----END PGP SIGNATURE-----

**Comment by sjPlot** [comment]
So, what is the current state of this issue? Still open?

**Comment by oziphantom** [comment]
I would say it is closed, there are other issues opened about this issue.
