### ISSUE TITLE
Backslashes are eaten on Windows

### ISSUE THREAD

**Issue by sjPlot** [sjPlot/Relaunch64#20]
I get this error when trying to compile

Error: Unable to access jarfile C:rogram Files (x86)ickAssemblerickAss.jar

Seems like it ate the \ chars and the first char of each folder/filename.

The script i made by dragging files to the script window. Worked perfectly in v3.3.3

I am new to Relaunch64 so i might be doing something wrong :)

From the log:

[INFO] Executing script "KickAss"
[INFO] Processing script-line: java -jar "C:\Program Files (x86)\KickAssembler\KickAss.jar" RSOURCEFILE
[INFO] Converted script-line: java -jar "C:\Program Files (x86)\KickAssembler\KickAss.jar" labyrint 2.asm
[WARNING] Undefined escape sequence: \P
[WARNING] Undefined escape sequence: \K
[WARNING] Undefined escape sequence: \K

**Comment by sjPlot** [comment]
Converting command line works as intended, probably a JRE issue...

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Converting command line works as intended, probably a JRE issue...

Not sure. I'll have a look sometime later.

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlXwiJwACgkQyBOVYiJltRZxWwCgpUT9+PuhNCiZb67Li5i+Xd94
bVcAmwT1Nx9qoQCPBaVEfjoGxq1ScP+w
=hwO4
-----END PGP SIGNATURE-----

**Comment by sjPlot** [comment]
I found the bug. It's due to [https://github.com/sjPlot/Relaunch64/pull/16](this commit).

See lines 507ff in [this file](https://github.com/sjPlot/Relaunch64/blob/master/src/de/relaunch64/popelganda/util/Tools.java):

            if ((flags & WITHIN_ESCAPE) != 0) {
                switch (character)
                {
                    case '"':
                    case '\\':
                        token.append(character);
                        break;
                    
                    default:
                        ConstantsR64.r64logger.log(Level.WARNING, "Undefined escape sequence: \\{0}", character);
                }

                flags ^= WITHIN_ESCAPE;
                continue;
            }

**Comment by davidqhogan** [comment]
It is functioning as I intended - IF you are using quoted parameters, then to represent a regular \ character you need to specify \\ which is a pretty standard escaping mechanism.

i.e. "C:\\Program Files (x86)\\KickAssembler\\KickAss.jar" will fix this case

**Comment by sjPlot** [comment]
Ok, thanks for clarification. I labelled this as "bug" because it broke user scripts (you could simply use single backslashes in quotes paths before).

**Comment by davidqhogan** [comment]
Oh - I didn't think quotes worked before I added them? Sorry if I broke existing scripts.

**Comment by sjPlot** [comment]
Yes, file paths with whitespace have been separated into multiple "tokens" - however, the ProcessBuilder seems to "concatenate" all single tokens with spaces to pass them to the command line.

Thus, 
1. "E:\file path\acme.exe" were split into `"E:\file` and `path\acme.exe"`
2. and then seemed to be passed over as `"E:\file path\acme.exe"` (concatenated with ` `) again.

That's why it worked. Is it OK to remove the escape check? Then, the tokenizer would return `"E:\file path\acme.exe"` as one token, and users don't have to change their former user scripts.

**Comment by davidqhogan** [comment]
That's strange - that's not how it works on OS X. For example, having created the file "/tmp/test file"\ , the following code

```java
List<String> tokens = new ArrayList<String>();
			
tokens.add("ls");
tokens.add("-l");
tokens.add("\"/tmp/test");
tokens.add("file\"");
		
Process pb = new ProcessBuilder(tokens).inheritIO().start();
pb.wait();
```

fails with:

```
ls: "/tmp/test: No such file or directory
ls: file": No such file or directory
```

Which indicates that each arg, with quote is being escaped before being passed to the shell. The effective command in this case is

```
$ ls -l \"/tmp/test file\"
ls: "/tmp/test: No such file or directory
ls: file": No such file or director
```

Adding a space to the end of '"/tmp/test' or before 'file"' doesn't fix it. This is the behaviour I would expect of the ProcessBuilder api - each argument in the list is escaped as appropriate to be considered a single element by the shell.

For the record I did put some thought into making this backwards compatible - I hadn't realised that Windows behaved differently in this case.

The escape mechanism is only really there to support paths containing a " character - and to be fair I doubt anyone really needs this. So yes - I think it makes sense to remove the escaping mechanism within quoted tokens.

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> The escape mechanism is only really there to support paths containing a "
> character - and to be fair I doubt anyone really needs this. So yes - I
> think it makes sense to remove the escaping mechanism within quoted 
> tokens.

Easiest and least painful method, I agree with this.

Otherwise we could go down the road below to emulate the behaviour of shell
on the platform, which is rather painful:

http://blogs.msdn.com/b/twistylittlepassagesallalike/archive/2011/04/23/everyo
ne-quotes-arguments-the-wrong-way.aspx

http://resources.mpi-inf.mpg.de/departments/rg1/teaching/unixffb-ss98/quoting-
guide.html

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iEYEARECAAYFAlXxYZsACgkQyBOVYiJltRa3PACg820Ncg8fExrVtHyDf7zuLEhd
n88AnRT+peaJefQSXwH3MS2eYw5yRa/r
=FpJB
-----END PGP SIGNATURE-----

**Comment by sjPlot** [comment]
Closed by https://github.com/sjPlot/Relaunch64/commit/d6c9cb92cb9935f116dbdf87f222f3e2da40d362
