### ISSUE TITLE
Local labels break autocomplete

### ISSUE THREAD

**Issue by oziphantom** [sjPlot/Relaunch64#21]
Hi

Been seeing the auto complete system break randomly a lot when programming, but last night I finally worked out the cause... local labels
So if I have
myFunc
  ldx # kThings. (press space + ctrl ) autocomplete works
one I get to 
myFunc
  ldx # kThings.Count
_loop
  lda kVectors. autocomplete doesn't work any more, if I remove the _loop it works again

3.3.4 20150517, Windows 10, Tass 64 mode, Java version 8 Update 45 (build 1.8.0_45_b14)

**Comment by soci64** [comment]
Should be fixed now, thanks!

**Comment by oziphantom** [comment]
Awesome thanks

**Comment by oziphantom** [comment]
When will the exes be updated? Or is there a doc on how to build the app on Windows?

**Comment by sjPlot** [comment]
I can release an update / binaries of devel-build tonight, when I'm back from work.

**Comment by sjPlot** [comment]
Ok, binaries for testing are available:
https://sourceforge.net/projects/relaunch64/files/devel/

Could you please check if the bug is fixed?

**Comment by oziphantom** [comment]
Fixed.
