### ISSUE TITLE
unfold on jump from Goto Sidebar?

### ISSUE THREAD

**Issue by oziphantom** [sjPlot/Relaunch64#25]
Can it be made so if I click on a function in the Goto Sidebar and said function is Folded in the main code view, instead of just putting the folded line on the screen that it also unfolds it?

**Comment by sjPlot** [comment]
I've uploaded binaries for testing here:
https://sourceforge.net/projects/relaunch64/files/devel/

**Comment by oziphantom** [comment]
Confirming fix.
