### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by oziphantom** [sjPlot/Relaunch64#30]
How do you build the code, I tried but I get missing libs like Swing and some others, are there instructions somewhere?

**Comment by sjPlot** [comment]
I'm using NetBeans to build the binaries. Beside the jdom and jTextArea libraries, I'm using the appframework-1.0.3.jar, swing-worker-1.1.jar and swing-layout-1.0.4.jar. All parts of the NetBeans IDE or downloadable via the plug-in center of NetBeans.
