### ISSUE TITLE
3.3.7-2 F6 does not run secondary script

### ISSUE THREAD

**Issue by oziphantom** [sjPlot/Relaunch64#33]
In 3.3.7-2 pressing F6 does not run the script, at least it does not report the results in the Assembler Log. Selecting "Run alternative Script" from the Source menu does run it. 
Windows-10 running from the .jar file 64tass mode.

**Comment by sjPlot** [comment]
ok, I'll look at the keybindings for the menu actions. Perhaps I have double-declared the F6-key?

**Comment by sjPlot** [comment]
It seems that F6 does in general not work on Windows... I'll look for an alternative keybinding.

**Comment by oziphantom** [comment]
F6 seems to toggle the selection between tab groups. Ie. from the main tabs to/from the Log tabs. 

Shift+F5?
