### ISSUE TITLE
3.3.7-2 Scripts with RGB64 do not ignore warnings.

### ISSUE THREAD

**Issue by oziphantom** [sjPlot/Relaunch64#34]
From CSDB
"I have added an option to add a second run-script, which may be used for debugging only. So the script that also runs the emulator can use the "R64BG"-option, which doesn't log warnings, and an alternative build-script for debugging can be run without starting the emulator (hence, R64BG is not needed)."
Both F5 script that uses R64BG command to run vice will stop on a warning msg. 
And F6 build only script that does not use R64BG command or run vice will stop on a warning msg. 
This seems inconsistent with the quote above.

Windows 10 + 64Tass 

I will rebuild my tass using latest latest src to see if that changes anything.

**Comment by sjPlot** [comment]
For me, following script works and does not block Relaunch64:

```
C:\Users\Standardbenutzer\Documents\Yavin4\C64\Tools\acme\acme.exe --outfile ROUTFILE --format cbm RSOURCEFILE
R64BG "C:\Program Files\Vice64\x64.exe" ROUTFILE
```

And yes, a compiler warning should be thrown as long as you don't put a "R64BG" at the beginning of the script line for the compiler as well. Was it that what you meant?

**Comment by oziphantom** [comment]
aha putting RGB64 upon the "assemble" line will ignore warnings, well it ignores everything and displays no assembler output.

**Comment by sjPlot** [comment]
yes, that is the intention of the _R64BG_ argument. :-)
So you want that the compiler finishes compiling regularly, also if warnings occur, and then VICE should compute the compiled prg-file?

**Comment by oziphantom** [comment]
Yeah
Build - has errors - script stops
Build - has warnings - VICE runs

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Yeah Build - has errors - script stops Build - has warnings - VICE runs

I still don't see the problem. This works for me:

R64 -iw
64tass -a SOURCEFILE -o OUTFILE
R64BG x64 OUTFILE

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----

iEYEARECAAYFAlfNpOsACgkQyBOVYiJltRbu3QCgjTMEDptxQznmlBukj9r/UcHS
taEAnj55YLUXKEGb0fbSpIpRlf9h42ZS
=omuv
-----END PGP SIGNATURE-----

**Comment by oziphantom** [comment]
R64 -iw fixes it. 
I looked in the Preferences for a ignore warnings option, its in the script toggle commands. Got it
