### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by anchor76** [sjPlot/Relaunch64#40]
hello, i getting an error message when i try to start the latest reaunch64.exe (v3.3.7.0)
"an error occured while starting the application"
os: win7 64bit, java 8 installed.
_edit: relaunch64.jar also not starting on my machine._

**Comment by strengejacke** [comment]
Did it work before, or has it never been working?

**Comment by anchor76** [comment]
i use total commander for launch apps. if i unpack the exe, and launch, its not working. (i tried two older versions too) if i entering the zip as folder, and execute the exe from it, it works ... so weird ... maybe the command line arguments differs in the two cases.
