### ISSUE TITLE
Update text editor component to jEdit-texarea 5.2

### ISSUE THREAD

**Issue by sjPlot** [sjPlot/Relaunch64#8]
Somewhen in the future, when we have some time left, we could update the editor-component...

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Somewhen in the future, when we have some time left, we could update the 
> editor-component...

I've compiled 5.2.0:
http://singularcrew.hu/temp/jedit-textArea.jar

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlTZ+mEACgkQyBOVYiJltRa3pgCg7X2XUQxNnKk8JsQmx1Yt7jDF
+KYAoJxIkVBcd/0ci4rFZvZa6rAwPoyW
=gCjd
-----END PGP SIGNATURE-----

**Comment by sjPlot** [comment]
Thanks, I have downloaded the jar. Will include it in the next development snapshot!
