### ISSUE TITLE
Font Size?

### ISSUE THREAD

**Issue by gerroon** [sjPlot/Relaunch64#9]
Hi

The fonts are too small on highres screens. It would be great if there was a way to resize the fonts.

thanks

**Comment by sjPlot** [comment]
See Menu Options => Preferences => Tab Editor => Editor Font. Do you mean that?

**Comment by gerroon** [comment]
sjPlot

Yes that works for the editor. However the menu fonts and everything else is still to small ;(

Btw this is a nice tool. Thanks again

**Comment by soci64** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Hi
> 
> The fonts are too small on highres screens. It would be great if there
> was a way to resize the fonts.

The fonts are dependent on the OS DPI settings. Make sure it's set up there
correctly. This was corrected long ago, before that I got tiny fonts on my
144 DPI display too.

- -- 
						    -soci-
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlT5XbAACgkQyBOVYiJltRbT7ACbBqKjB9o17wFIBNJ12Pp13mY/
JzoAmgO3HC5j48/2RaAWn3zYPO9YUZA2
=/mXJ
-----END PGP SIGNATURE-----

**Comment by gerroon** [comment]
thanks, I will check it out.

**Comment by c64whiz** [comment]
I have already up'd my DPI to 150 and I still have small fonts on the GUI:

![pic](https://user-images.githubusercontent.com/410595/79282322-6dcb5580-7ea4-11ea-99fc-5a4694468919.png)

**Comment by c64whiz** [comment]
Per my last comment, I add this for anyone else who runs into the issue.  I'm running Linux with OpenJDK 11.  To fix the GUI font scaling issue, adding the following to the command line worked on my Debian Buster system:

              `-Dsun.java2d.uiScale=2.5`

You may need to play with the _2.5_ to get it to your liking.

--C64Whiz
